### ISSUE TITLE
Full paths to modules are being left in production output bundles

### ISSUE THREAD

**Issue by roemhildtg** [OpenNTF/dojo-webpack-plugin#185] opened 2018-11-02 16:24 UTC
I'm working with the arcgis js api and webpack plugin which uses this plugin under the hood. 

I'm running into constant issues where sometimes after running a build, I'll run into errors where the workers fail to load. It doesn't happen all of the time, and it sometimes resolves itself for no apparent reason. I realize this might not even be related to your plugin, but if you have any ideas to offer, I would love to hear them. This is sort of a last ditch effort in fixing this reoccurring issue. 

Looks like this is the dojo config the esri webpack plugin uses:

These are the errors I'm getting:

## 1

```
VM53057:1 Access to XMLHttpRequest at 'file:///C:/Users/<username>/web/dl2-datafi/node_modules/arcgis-js-api/core/workers/worker.js' from origin 'http://lvh.me:9000' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
```

## 2

```
[esri.core.workers] Failed to create Worker. Fallback to execute module in main thread 
t {name: "request:server", message: "Unable to load C:/Users/<username>/web/dl2-datafi-…es/arcgis-js-api/core/workers/worker.js status: 0", details: {…}}
details: {url: "C:/Users/<username>/web/dl2-datafi/node_modules/arcgis-js-api/core/workers/worker.js", requestOptions: {…}, getHeader: ƒ, httpStatus: 0, subCode: undefined, …}
message: "Unable to load C:/Users/<username>/web/dl2-datafi/node_modules/arcgis-js-api/core/workers/worker.js status: 0"
name: "request:server"
```

![image](https://user-images.githubusercontent.com/5471079/47927342-0462ad00-de91-11e8-9f7a-827d774cce6e.png)

## 3

```
Error: Module not found: C:/Users/<username>/web/dl2-datafi/node_modules/arcgis-js-api/views/2d/layers/features/Pipeline
```

![image](https://user-images.githubusercontent.com/5471079/47927305-e6954800-de90-11e8-9175-0da13c9f1c4f.png)

Theres a few concerns here: 
 - First the obvious one is my app won't load. That makes me sad.
 - Second the username of my account is actually getting put into the ouput build, which I'm not a big fan of either. 

If you have any thoughts, I'd love to hear them.

Packages | Version
-----------|---------
Webpack: | 4.24.0
Dojo-webpack-plugin: | 2.7.6
ArcGIS webpack plugin: |  4.9.0
Dojo: |  1.14.0
arcgis-js-api: | 4.9.3

Dojo.config: 
<details>

```json
{
    "hasCache": {
        "webpack": 1,
        "host-browser": 1,
        "dom": 1,
        "dojo-loader": 1,
        "dojo-has-api": 1,
        "dojo-dom-ready-api": 1,
        "dojo-sniff": 1,
        "dojo-test-sniff": 1,
        "config-deferredInstrumentation": false,
        "config-tlmSiblingOfDojo": 1,
        "dojo-config-api": 0,
        "esri-promise-compatibility": 1,
        "esri-webpack": 1,
        "dom-addeventlistener": true,
        "touch-events": false,
        "pointer-events": true,
        "device-width": 1536,
        "dom-attributes-explicit": true,
        "dom-attributes-specified-flag": false,
        "extend-dojo": 1,
        "dojo-guarantee-console": 1,
        "dojo-debug-messages": false,
        "dojo-modulePaths": 1,
        "dojo-moduleUrl": 1,
        "air": false,
        "webkit": 537.36,
        "chrome": 70,
        "mac": false,
        "quirks": false,
        "svg": true,
        "dom-contains": true,
        "css-user-select": "userSelect",
        "json-parse": true,
        "json-stringify": true,
        "event-stopimmediatepropagation": true,
        "config-useDeferredInstrumentation": false,
        "activex": false,
        "dojo-force-activex-xhr": false,
        "dojo-preload-i18n-Api": 1,
        "dojo-v1x-i18n-Api": 1,
        "esri-secure-context": false,
        "esri-wasm": true,
        "esri-workers": true,
        "esri-url-encodes-apostrophe": true,
        "esri-webgl": true,
        "esri-webgl-high-precision-fragment": true,
        "esri-webgl-vertex-shader-samplers": true,
        "esri-webgl-element-index-uint": true,
        "esri-webgl-standard-derivatives": true,
        "esri-webgl-instanced-arrays": true,
        "esri-webgl-major-performance-caveat": false,
        "esri-featurelayer-webgl": true,
        "esri-featurelayer-webgl-labeling": true,
        "esri-webgl2": true,
        "dojo-config-addOnLoad": 1,
        "dom-quirks": false,
        "events-mouseenter": true,
        "events-mousewheel": true,
        "events-keypress-typed": true,
        "config-selectorEngine": "acme",
        "dom-qsa2.1": true,
        "dom-matches-selector": true,
        "dom-qsa": true,
        "dojo-config-require": 1,
        "esri-promise-compatibility-deprecation-warnings": true,
        "dijit-legacy-requires": false,
        "dojo-bidi": false,
        "highcontrast": false,
        "esri-workers-arraybuffer-transfer": true,
        "esri-svg-classlist": true
    },
    "paths": {},
    "pathsMapProg": [],
    "packs": {
        "dojo": {
            "main": "main",
            "name": "dojo",
            "location": "./dojo",
            "lib": "."
        },
        "dijit": {
            "main": "main",
            "name": "dijit",
            "location": "./dijit",
            "lib": "."
        },
        "dojox": {
            "main": "main",
            "name": "dojox",
            "location": "./dojox",
            "lib": "."
        },
        "esri": {
            "main": "kernel",
            "name": "esri",
            "location": "./arcgis-js-api"
        },
        "@dojo": {
            "main": "main",
            "name": "@dojo",
            "location": "./@dojo",
            "lib": "."
        },
        "cldrjs": {
            "main": "dist/cldr",
            "name": "cldrjs",
            "location": "./cldrjs"
        },
        "globalize": {
            "main": "dist/globalize",
            "name": "globalize",
            "location": "./globalize"
        },
        "tslib": {
            "main": "tslib",
            "name": "tslib",
            "location": "./tslib"
        },
        "moment": {
            "main": "main",
            "name": "moment",
            "location": "./moment",
            "lib": "."
        },
        "dstore": {
            "main": "main",
            "name": "dstore",
            "location": "./dojo-dstore",
            "lib": "."
        },
        "maquette": {
            "main": "dist/maquette.umd",
            "name": "maquette",
            "location": "./maquette",
            "resourceTags": {}
        },
        "maquette-css-transitions": {
            "main": "dist/maquette-css-transitions.umd",
            "name": "maquette-css-transitions",
            "location": "./maquette-css-transitions",
            "resourceTags": {}
        },
        "maquette-jsx": {
            "main": "dist/maquette-jsx.umd",
            "name": "maquette-jsx",
            "location": "./maquette-jsx",
            "resourceTags": {}
        }
    },
    "aliases": [],
    "mapProgs": [
        ["globalize", [
            ["cldr/supplemental", "cldrjs/dist/cldr/supplemental", {}, 17],
            ["cldr/unresolved", "cldrjs/dist/cldr/unresolved", {}, 15],
            ["cldr/event", "cldrjs/dist/cldr/event", {}, 10],
            ["cldr", "cldrjs/dist/cldr", {}, 4]
        ], {}, 9]
    ],
    "modules": {},
    "cache": {},
    "locale": "en-us",
    "baseUrl": "./",
    "afterOnLoad": true
}
```

</details>

Webpack config:

<details>

```javascript
const ArcGISPlugin = require('@arcgis/webpack-plugin');
const HtmlWebPackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const path = require('path');
const MinifyPlugin = require('terser-webpack-plugin');

module.exports = {
    entry: {
        'main': './src/index.js',
    },
    output: {
        filename: '[name].[chunkhash].js',
        publicPath: '',
    },

    plugins: [
        new CleanWebpackPlugin(['dist', 'build']),
        new ArcGISPlugin({
            useDefaultAssetLoaders: false,
        }),
        new MiniCssExtractPlugin({
            // Options similar to the same options in webpackOptions.output
            // both options are optional
            filename: './[name].[hash].css',
            chunkFilename: './[id].[hash].css',
        }),
        new HtmlWebPackPlugin({
            template: './src/index.html',
            filename: './index.html',
            chunksSortMode: 'none',
        }),
        new HtmlWebPackPlugin({
            inject: false,
            template: './src/oauth-callback.html',
            filename: './oauth-callback.html',
            chunksSortMode: 'none',
        }),
    ],

    module: {
        rules: [{
            test: /\.stache$/,
            use: [{loader: 'raw-loader'}],
        }, {
            test: /\.layout$/,
            use: [{loader: 'raw-loader'}],
        }, {
            test: /\.js$/,
            exclude: /node_modules/,
            use: [{
                loader: 'babel-loader',
                options: {
                    sourceMap: true,
                },
            }],
        }, {
            test: /\.css$/,
            use: [
                MiniCssExtractPlugin.loader,
                {loader: 'css-loader', options: {sourceMap: true}},
                'postcss-loader', {
                    loader: 'resolve-url-loader',
                    options: {includeRoot: true},
                },
            ],
        }, {
            test: /\.less$/,
            use: [
                MiniCssExtractPlugin.loader,
                'css-loader',
                'postcss-loader',
                'less-loader',
            ],
        }, {
            test: /\.scss$/,
            use: [
                MiniCssExtractPlugin.loader,
                {loader: 'css-loader', options: {sourceMap: true}},
                'postcss-loader', {
                    loader: 'resolve-url-loader',
                    options: {includeRoot: true, sourceMap: true},
                }, {
                    loader: 'sass-loader',
                    options: {
                        sourceMap: true,
                    },
                },
            ],
        }, {
            test: /\.(jpe?g|png|gif|webp)$/,
            loader: 'url-loader',
            options: {
                // Inline files smaller than 10 kB (10240 bytes)
                limit: 10 * 1024,
            },
        }, {
            test: /\.(wsv|ttf|otf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
            use: [{
                loader: 'file-loader',
                options: {
                    name: 'build/[name].[ext]',
                },
            }],
        }],
    },


    resolve: {
        extensions: ['.wasm', '.js', '.json'],
        modules: [
            path.resolve(__dirname, '/src'),
            path.resolve(__dirname, 'node_modules/'),
        ],
        alias: {
            'esri': 'arcgis-js-api',
            'sweetalert2$': 'sweetalert2/dist/sweetalert2',
            'moment': 'moment/moment',
        },
    },


    node: {
        process: false,
        global: false,
        fs: 'empty',
    },


    externals: [
        (context, request, callback) => {
            if (/pe-wasm$/.test(request)) {
                return callback(null, 'amd ' + request);
            }
            callback();
        },
    ],

    optimization: {
        minimizer: [
            new MinifyPlugin({
                parallel: true,
            }),
        ],
    },
};

```
</details>

EsriConfig.js for workers:

<details>

```
import esriConfig from 'esri/config';

const DEFAULT_WORKER_URL = 'https://js.arcgis.com/4.9/';
const DEFAULT_LOADER_URL = `${DEFAULT_WORKER_URL}dojo/dojo-lite.js`;

esriConfig.workers.loaderUrl = DEFAULT_LOADER_URL;
esriConfig.workers.loaderConfig = {
    baseUrl: `${DEFAULT_WORKER_URL}dojo`,
    has: {
        'esri-featurelayer-webgl': 1,
    },
    packages: [
        {name: 'esri', location: `${DEFAULT_WORKER_URL}esri`},
        {name: 'dojo', location: `${DEFAULT_WORKER_URL}dojo`},
        {name: 'dojox', location: `${DEFAULT_WORKER_URL}dojox`},
        {name: 'dstore', location: `${DEFAULT_WORKER_URL}dstore`},
        {name: 'moment', location: `${DEFAULT_WORKER_URL}moment`},
        {name: '@dojo', location: `${DEFAULT_WORKER_URL}@dojo`},
        {
            name: 'cldrjs',
            location: `${DEFAULT_WORKER_URL}cldrjs`,
            main: 'dist/cldr',
        },
        {
            name: 'globalize',
            location: `${DEFAULT_WORKER_URL}globalize`,
            main: 'dist/globalize',
        },
        {
            name: 'maquette',
            location: `${DEFAULT_WORKER_URL}maquette`,
            main: 'dist/maquette.umd',
        },
        {
            name: 'maquette-css-transitions',
            location: `${DEFAULT_WORKER_URL}maquette-css-transitions`,
            main: 'dist/maquette-css-transitions.umd',
        },
        {
            name: 'maquette-jsx',
            location: `${DEFAULT_WORKER_URL}maquette-jsx`,
            main: 'dist/maquette-jsx.umd',
        },
        {name: 'tslib', location: `${DEFAULT_WORKER_URL}tslib`, main: 'tslib'},
    ],
};
```

</details>

## Related:

https://github.com/Esri/arcgis-webpack-plugin/issues/22
https://stackoverflow.com/questions/51986624/webpack-babel-loader-outputting-full-c-drive-urls-in-bundles/52007420#52007420

**Comment by chuckdumont** [comment] 2018-11-02 18:23
Not sure about the cause of the error, but regarding the full path URLs in bundles, I know that webpack uses the full path URL as the module id in development mode, but in production mode, it uses an integer ids.  Do you still see this issue when you use mode:'production'?

**Comment by roemhildtg** [comment] 2018-11-02 18:49
Yup, I do see stuff like this in the production build:

```javascript
            }
            throw new Error("Unsupported require call")
        }
        r.toUrl = e, r.toAbsMid = t, r.absMids = {}, r.absMidsById = [], r.async = 1;
        var u = this || window;
        if (i({
                "can-define/map/map": 6,
                "can-define/list/list": 46,
                "can-stache": 52,
                "@wsb/dl-util/lib/registryAsync": 77,
                "can-view-model": 86,
                "can-route": 158,
                "spectre-canjs/util/string/string": 160,
                "esri/config": 224,
                "C:/Users/<username>/web/dl2-datafi-/node_modules/arcgis-js-api/config": 224,
                "babel-polyfill": 254,
                "C:/Users/<username>/web/dl2-datafi-/node_modules/babel-loader/lib/index.js??ref--6-0!C:/Users/<username>/web/dl2-datafi-/src/config/esri/esriConfig": 456,
                "C:/Users/<username>/web/dl2-datafi-/node_modules/babel-loader/lib/index.js??ref--6-0!C:/Users/<username>/web/dl2-datafi-/src/config/widgets/widgets": 457,
                "C:/Users/<username>/web/dl2-datafi-/node_modules/babel-loader/lib/index.js??ref--6-0!C:/Users/<username>/web/dl2-datafi-/src/config/map/layers": 458,
                "C:/Users/<username>/web/dl2-datafi-/node_modules/babel-loader/lib/index.js??ref--6-0!C:/Users/<username>/web/dl2-datafi-/src/config/map/view": 459,
                "C:/Users/<username>/web/dl2-datafi-/node_modules/babel-loader/lib/index.js??ref--6-0!C:/Users/<username>/web/dl2-datafi-/src/styles/main.scss": 460
```

**Comment by chuckdumont** [comment] 2018-11-02 20:03
OK, yeah.  That's dojo-webpack-plugin doing that.  I'll look into fixing

**Comment by roemhildtg** [comment] 2018-11-09 02:33
I put together simplified demo of the other issue(s) I'm having. If you have any suggestions on things I could try, I'd really appreciate them. 

https://github.com/roemhildtg/esri-webpack-bug/tree/master/dist-vector-basemap-bug

**Comment by roemhildtg** [comment] 2018-11-12 19:46
Hey Chuck, just wondering if you by chance had an update on this. I'd be willing to take a stab at fixing this if you could point me in the right direction, because this is currently preventing us from building our application successfully.

**Comment by chuckdumont** [comment] 2018-11-13 13:43
Sorry, I've been busy with my day job and haven't had much time to spend on this.  I did clone your test case and built it (no issues) but I couldn't run either the `start` or `serve` scripts, and I didn't dig any further.  Running `serve` complains about `http-server` not found, and running `start` the compiler runs but appears to hang indefinitely.

I'm hoping to have some time to spend on this in the next couple weeks.  In the mean time, I don't really know what direction to point you because I don't have any sense about what the problem might be.

When you encounter this issue, does the app fail consistently until you rebuild, or does it fail intermittently?

**Comment by roemhildtg** [comment] 2018-11-13 20:09
Completely understand, no worries on the delay. 

 I'm not sure why npm start was hanging for you, that's a new one. I do know it takes a long time to build webpack-dojo projects, mine usually last around 5-8 minutes for whatever reason for the first build. Yes, its painful, but the rebuilds happen much faster...5-6 seconds as the webpack dev server continues running.

Basically when I encounter this issue, the only solution is to comment out the dynamic imports, and make them static imports in the main module, run the build process (npm start) and then replace the static imports with the dynamic imports.

So, I have a simpler demo that you can try here: This is forked directly from esri's webpack demo for aid in diagnosing the issue. 

https://github.com/roemhildtg/jsapi-resources/tree/master/4.x/webpack/demo#steps-to-get-to-bug

**Comment by chuckdumont** [comment] 2018-11-19 14:54
Please try pre-release version 2.7.7-0 and verify it resolves your issue with no regressions.  Thanks.

**Comment by chuckdumont** [comment] 2018-11-20 20:05
Closed by merge of PR.  Re-opening pending confirmation of fix.

**Comment by chuckdumont** [comment] 2018-11-20 20:08
@roemhildtg, please try pre-release version 2.7.7-1.  This should fix your other issue with the Module not found errors.  At least it does with the test case.

**Comment by chuckdumont** [comment] 2018-11-23 12:06
@roemhildtg I did a couple more iterations on this fix.  Please test with 2.7.7-4.

**Comment by cmdcolin** [comment] 2018-11-26 12:47
I saw this problem where modules were missing with webpack 4 but 2.7.7-4 does fix it for me! Awesome 👍

**Comment by chuckdumont** [comment] 2018-11-30 14:56
Both of the issues reported here (full paths to modules and Module not found errors) are fixed in v2.7.7.

**Closed by chuckdumont** 2018-11-30 14:56 UTC

**Comment by wmakley** [comment] 2019-06-14 19:14
I just ran into this with many URL's in my app. Not sure what I am doing wrong:

404 not found on load:
`http://localhost:8080/home/william/myapp/js/node_modules/dojo/resources/blank.gif`

Obviously that is the wrong URL. When I was using Dojo, this was controlled by the "baseUrl" option in dojoConfig. That seems to be ignored with this loader.

Anything I can try?

**Comment by chuckdumont** [comment] 2019-06-14 19:43
@wmakley, it sounds like you're specifying an absolute path for baseUrl instead of a relative path.  You can do that, but then you need to take steps to ensure that the correct value is used at runtime on the client.  Check out the [environment](https://github.com/OpenNTF/dojo-webpack-plugin#environment) and [buildEnvironment](https://github.com/OpenNTF/dojo-webpack-plugin#buildenvironment) options you can specify in the dojo-webpack-plugin config.

**Comment by wmakley** [comment] 2019-06-14 20:37
Thanks, it hurt my head but your example loaderConfig worked + those environment options worked to make it respect the correct options at runtime and build time. I also needed to place it directly on the page to work with webpack-dev-server.
